app = "attend-pb-mohamed-260417"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8090
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "pb_data"
  destination = "/pb_data"
